name: Publish Docker Images

on:
  push:
    branches: [ stable ]
#    paths:
#    - Dockerfile

jobs:
  push_to_registry:
    name: Push Docker images to Dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Publish aflpp to Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: aflplusplus/aflplusplus:latest
